name: CI/CD Pipeline

on:
  push:
    branches:
      - devops-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t ecomm-app .

    - name: Run Docker Container
      run: docker run -d -p 8080:3000 --name ecomm-app-container ecomm-app

    - name: Wait for App to Start
      run: sleep 10

    - name: Print Container Logs (for debugging)
      run: docker logs ecomm-app-container || true

    - name: Validate App Is Running on localhost:8080
      run: curl --retry 10 --retry-delay 6 http://localhost:8080 || exit 1

    - name: Clean Up Docker Container
      if: always()
      run: docker rm -f ecomm-app-container || true
